# permissions for end users to edit containerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerjob-editor-role
rules:
- apiGroups:
  - container.vnv.wrstudio.cloud
  resources:
  - containerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.vnv.wrstudio.cloud
  resources:
  - containerjobs/status
  verbs:
  - get
