# permissions for end users to view containerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerjob-viewer-role
rules:
- apiGroups:
  - container.vnv.wrstudio.cloud
  resources:
  - containerjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - container.vnv.wrstudio.cloud
  resources:
  - containerjobs/status
  verbs:
  - get
